name: Build OpenWrt Packages (PR)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  build:
    name: Build (${{ matrix.arch }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64
          - mipsel_24kc
          - mips_mips32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK packages with OpenWrt SDK action
        uses: openwrt/gh-action-sdk@v10
        env:
          ARCH: "${{ matrix.arch }}-openwrt-25.12"
          FEEDNAME: boinc_openwrt
          PACKAGES: "period-search binary-radio-pulsar-search fftw3 gsl"

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/boinc_openwrt/
          if-no-files-found: warn
